spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lawmatedb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dev
    password: devpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, validate 등 선택
    show-sql: true

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha
      tryItOutEnabled: true

openai:
  api:
    key: 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
